// <auto-generated />
namespace _12_GeneralStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class UpdatedPurchasedQuantitytoPurchaseQuantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatedPurchasedQuantitytoPurchaseQuantity));
        
        string IMigrationMetadata.Id
        {
            get { return "202105262005367_Updated 'PurchasedQuantity' to 'PurchaseQuantity'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
